version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 4000:4000
    entrypoint: dockerize -wait tcp://db:3306 -timeout 90s sh -c "yarn && yarn prisma:generate && yarn build && yarn seed && yarn start"
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - '3306'
    command:
      - "mysqld"
      - "--max-connections=1000"
      - "--sql-mode=ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_FIELD_OPTIONS,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,ANSI,DB2,MAXDB,MSSQL,MYSQL323,MYSQL40,ORACLE,POSTGRESQL,TRADITIONAL"
      - "--wait-timeout=28800"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
