-- AlterTable
ALTER TABLE `employee` MODIFY `status` ENUM('ATIVO', 'INATIVO') NULL,
    MODIFY `cpf` VARCHAR(191) NULL,
    MODIFY `birthDate` DATETIME(3) NULL,
    MODIFY `gender` ENUM('HOMEM', 'MULHER') NULL,
    MODIFY `maritalStatus` ENUM('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'VIUVO') NULL,
    MODIFY `nationality` VARCHAR(191) NULL,
    MODIFY `placeOfBirth` VARCHAR(191) NULL,
    MODIFY `position` VARCHAR(191) NULL,
    MODIFY `department` ENUM('ADMINISTRATIVO', 'OPERACIONAL', 'COMERCIAL', 'OUTRO', 'OPERACAO', 'VENDAS', 'ORCAMENTO', 'SUPERVISION', 'LOGISTICA', 'QUALIDADE', 'ATENDIMENTO_AO_CLIENTE', 'RECURSOS_HUMANOS', 'FINANCEIRO', 'MARKETING', 'PROJETOS', 'SEGURANCA_DO_TRABALHO', 'TI', 'COMPRAS', 'MANUTENCAO') NULL,
    MODIFY `paymentRegime` ENUM('CLT', 'CLTD', 'TERCEIRO') NULL,
    MODIFY `weeklyWorkload` VARCHAR(191) NULL;
