"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const customer_company_1 = require("../controllers/customer-company");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authenticate);
router.get('/', authMiddleware_1.requireAdmin, customer_company_1.customerCompanyController.getAll);
router.get('/:id', authMiddleware_1.requireAdmin, customer_company_1.customerCompanyController.getById);
router.post('/', authMiddleware_1.requireAdmin, customer_company_1.customerCompanyController.create);
router.put('/:id', authMiddleware_1.requireAdmin, customer_company_1.customerCompanyController.update);
router.delete('/:id', authMiddleware_1.requireAdmin, customer_company_1.customerCompanyController.delete);
exports.default = router;
