"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const employee_1 = require("../controllers/employee");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authenticate);
router.get('/', employee_1.employeeController.getAll);
router.get('/:id', employee_1.employeeController.getById);
router.post('/', employee_1.employeeController.create);
router.put('/:id', employee_1.employeeController.update);
router.delete('/:id', employee_1.employeeController.delete);
exports.default = router;
